{
    'name': 'EcoSphere - ESG Management Platform',
    'version': '17.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'ESG Management inside Odoo — Environmental, Social, Governance',
    'description': 'Measure, manage and improve ESG performance directly within Odoo.',
    'author': 'Team EcoSphere',
    'depends': [
        'base',
        'web',
        'hr',
        'purchase',
        'account',
        'hr_expense',
        'fleet',
        'mrp',
        'mail',
        'product',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/emission_factor_data.xml',
        'data/badge_data.xml',
        'data/demo_data.xml',
        'data/ir_cron_data.xml',
        'views/menu_views.xml',
        'views/department_views.xml',
        'views/environmental_views.xml',
        'views/custom_report_wizard_views.xml',
        'views/social_views.xml',
        'views/governance_views.xml',
        'views/gamification_views.xml',
        'views/dashboard_views.xml',
        'views/settings_views.xml',
        'report/report_actions.xml',
        'report/esg_reports.xml',
    ],
    'demo': [],
    'assets': {
        'web.assets_backend': [
            'ecosphere/static/src/scss/ecosphere_backend.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
